### ISSUE TITLE
investigate acars, dataminr messages in topic modeling

### ISSUE THREAD

**Issue by emiliecowen** [MIT-AI-Accelerator/c3po-model-server#194]

**Comment by lshinggg** [comment]
Met with Courtland to discuss experiment outputs. Consensus was that for the purposes of our Sponsor's use case, ACARS should be included with group of messages for topic modeling, and to not include Dataminr messages in the same topic model due to the dominant signal it carries. 

If we are to use Dataminr in the future, then it should be its own topic model.
